### ISSUE TITLE
[feat,refactor] 유저 정보 싱글톤 구현

### ISSUE THREAD

**Issue by centerfoward** [PockyProject/App#11]
기존에 유저 정보 일반 객체에 담아서 사용중이였으나, Favor -> Main 액티비티 간 화면 이동 시 객체 이동이 너무 번거롭고 비효율적이라 판단되어 
유저 정보를 싱글톤 객체에 담아서 관리하기로함.

**Comment by cdjsdjwkfgkrhtlvek** [comment]
확인했습니다~
