### ISSUE TITLE
[REFACTOR] Useless Func,File Delete

### ISSUE THREAD

**Issue by centerfoward** [PockyProject/App#32]
# 개요
필요없는 기능, 파일 삭제 및 정리

# 상세
현재 앱 내부에 사용하지 않거나 불필요하게 중복되어있는 기능들이 있음. 
이를 정리할 예정

**Comment by yolominwoo** [comment]
확인했습니다.
추후 삭제된 기능이나 불필요한 기능 엑셀로 정리 해주세용~
